- name: Run command to create a new key to use in rotation.
  local_action: shell {{role_path}}/scripts/aws_key_rotate.sh --create {{iam_username}}
  register: createkey
  delegate_to: localhost
  tags: create

#- debug:
#    var: createkey
#  tags: create

#- debug: msg="{{ command.stdout_lines.4 }}"
#- debug: msg="{{ command.stdout_lines.6 }}"

- name: Set fact for newly create AWS API ACCESS_KEY_ID and SECRET_ACCESS_KEY.
  set_fact:
    AWS_ACCESS_KEY_ID="{{ createkey.stdout_lines.2 }}"
    AWS_SECRET_ACCESS_KEY="{{ createkey.stdout_lines.4 }}"
  tags: create
  no_log: True

- debug: msg="Create new key for {{iam_username}} with KEYID={{ AWS_ACCESS_KEY_ID }} KEYSECRET={{ AWS_SECRET_ACCESS_KEY }} "
  tags: create
