- name: Update the file in the user directory that runs awscli
  become: yes
  file:
    path: /home/{{aws_cli_user}}/.aws
    state: directory
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0755

- name: Update the .aws/config file.
  template:
    src: templates/config.j2
    dest: /home/{{aws_cli_user}}/.aws/config
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0644
  become: yes

- name: Update the .aws/credentials file.
  template:
    src: templates/credentials.j2
    dest: /home/{{aws_cli_user}}/.aws/credentials
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0644
  become: yes
