#AWS key will be stored in the users home directory.  This will get that information.
- name: Get the path to the home directory for the user.
  shell: >
    getent passwd {{ aws_cli_user }} | cut -d: -f6
  changed_when: false
  register: user_home
  tags: debug

- name: debug output
  debug: var=user_home.stdout
  tags: debug

- name: Update the .aws file in the users home directory.
  become: yes
  file:
    path: '{{user_home.stdout}}/.aws'
    state: directory
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0755

- name: Update the .aws/config file.
  template:
    src: templates/config.j2
    dest: '{{user_home.stdout}}/.aws/config'
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0644
  become: yes

- name: Update the users .aws/credentials file.
  template:
    src: templates/credentials.j2
    dest: '{{user_home.stdout}}/.aws/credentials'
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0644
  become: yes
