- name: Update the .aws file in the users home directory.
  become: yes
  file:
    path: /home/{{aws_cli_user}}/.aws
    state: directory
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0755
  when: aws_cli_user not "root"

- name: Update the root .aws file in /root that runs awscli.
  become: yes
  file:
    path: /root/.aws
    state: directory
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0755
  when: aws_cli_user == "root"

- name: Update the .aws/config file.
  template:
    src: templates/config.j2
    dest: /home/{{aws_cli_user}}/.aws/config
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0644
  become: yes
  when: aws_cli_user not "root"

- name: Update the .aws/config file for root.
  template:
    src: templates/config.j2
    dest: /root/.aws/config
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0644
  become: yes
  when: aws_cli_user == "root"

- name: Update the users .aws/credentials file.
  template:
    src: templates/credentials.j2
    dest: /home/{{aws_cli_user}}/.aws/credentials
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0644
  become: yes
  when: aws_cli_user not "root"

- name: Update the roots .aws/credentials file.
  template:
    src: templates/credentials.j2
    dest: /root/.aws/credentials
    owner: "{{aws_cli_user}}"
    group: "{{aws_cli_user}}"
    mode: 0644
  become: yes
  when: aws_cli_user == "root"
