#This sets the necessary enviorment variables for AWS servers.
##Get the information of the custom facts.
- name: WINDOWS-Set the enviroment variables for AWS servers to access S3.
  win_environment:
    state: present
    name: AWS_ACCESS_KEY_ID
    value: "{{AWS_ACCESS_KEY_ID}}"
    level: machine

- name: Set the AWS_SECRET_ACCESS_KEY enviroment variable.
  win_environment:
    state: present
    name: AWS_SECRET_ACCESS_KEY
    value: "{{AWS_SECRET_ACCESS_KEY}}"
    level: machine

- name: Create .aws directory if it doesn't exist.
  win_file:
    path: C:\Users\{{aws_cli_user}}\.aws
    state: directory

- name: Touch the config files to make sure they are present.
  win_file:
    path: C:\Users\{{aws_cli_user}}\.aws\config
    state: touch

- name: Touch the credentials files to make sure they are present.
  win_file:
    path: C:\Users\{{aws_cli_user}}\.aws\credentials
    state: touch

- name: Set the config file in c:\Users directory from template.
  win_template:
    src: templates/config.j2
    dest: C:\Users\{{aws_cli_user}}\.aws\config

- name: Set the credentials file in c:\Users directory from template.
  win_template:
    src: templates/credentials.j2
    dest: C:\Users\{{aws_cli_user}}\.aws\credentials

- name: Restart "{{notify_service}}" because the variable is set and this service relies on AWS.
  win_service:
    name: "{{notify_service}}"
    state: restarted
  when: notify_service is defined
