# Run powershell command to get the enviorment variable for AWS_ACCESS_KEY_ID
- name: Print the existing windows enviroment variable key to expire.
  win_shell: "echo $Env:AWS_ACCESS_KEY_ID"
  register: winenv
  tags: winkey

#- debug:
#    var: winenv
#  tags: debug

#- debug: msg="{{ winenv.stdout_lines.0 }}"
#  tags: debug

- name: Set the fact for the key we will expire for Windows.
  set_fact:
    oldkey={{winenv.stdout_lines.0}}
  tags: winkey
  ignore_errors: yes

- debug:
    msg: "WARNING: I could not determine the ID of the previous key.  Only a new key will be created.  No key will be expired."
  when: not winenv.stdout_lines.0
